### ISSUE TITLE
Weird Mypy behaviour

### ISSUE THREAD

**Issue by kszmigiel** [kszmigiel/mypy-playground#1]
Hey!

Here's my `main.py` fragment for context:

```
...

ChildFromParent = Child.from_parent(Parent)

class Uncle:
      nephew = ChildFromParent()

reveal_type(Uncle.nephew.parent_and_child_method())
reveal_type(Uncle.nephew.child_only_method())
reveal_type(Uncle.nephew)
```

I've noticed that if:
1. I modify `plugin.py` file (no changes in logic, just add or delete a line)
2. Then run `mypy main.py`

I get:

```
~/P/mypy-playground ❯❯❯ mypy main.py
main.py:51: note: Revealed type is 'builtins.str'
main.py:52: note: Revealed type is 'builtins.str'
main.py:53: note: Revealed type is 'main.ChildFromParent'
```

Which is nice 😄  BUT, when I run exact same command again (without modifying `plugin.py` file), Mypy returns an error:

```
~/P/mypy-playground ❯❯❯ mypy main.py                                                                                                                                         ✘ 1
main.py:46: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.780
main.py:46: : note: please use --show-traceback to print a traceback when reporting a bug
```

Any ideas what's the reason for that, and what could be the solution? Such behavior seem a really strange for me, I'm considering to create an issue in Mypy repo 🤔

**Comment by sobolevn** [comment]
Can you please show what mypy outputs with `--show-traceback`?

**Comment by kszmigiel** [comment]
@sobolevn should do it by default, sorry

```
~/P/mypy-playground ❯❯❯ mypy main.py --show-traceback                                                                                                                        
main.py:46: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.780
Traceback (most recent call last):
  File "mypy/semanal.py", line 4691, in accept
  File "mypy/nodes.py", line 1062, in accept
  File "mypy/semanal.py", line 1943, in visit_assignment_stmt
  File "mypy/semanal.py", line 2194, in apply_dynamic_class_hook
  File "/Users/kacperszmigiel/Projects/mypy-playground/plugin.py", line 84, in create_new_manager_class_from_from_queryset_method
    method_node=sym.node)
  File "/Users/kacperszmigiel/Projects/mypy-playground/lib/helpers.py", line 353, in copy_method_to_another_class
    method_node.arguments[1:]):
AttributeError: attribute 'arguments' of 'FuncItem' undefined
main.py:46: : note: use --pdb to drop into pdb
```

**Comment by sobolevn** [comment]
Seems like there's an error somewhere in mypy. Can you please compare what happens inside `method_node.arguments[1:]` during successful and failed run?
